<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Home</title>

<script src="site_libs/header-attrs-2.18/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">My Website</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Home</h1>

</div>


<div id="introduction" class="section level1">
<h1>Introduction:</h1>
<p>As the pressure of population growth increases, many citizens in
developed countries face health-related issues when they get older. In
Us, health insurance can pay many medical costs, thus many families
would choose to buy medical insurances to prevent tremendous costs if
something unexpected happened.</p>
<p>In this condition, it is necessary to predict the health insurance
cost based on personal background information, which also benefits
insurance companies.</p>
<p>Here we get the dataset from kaggle, with variables age, bmi, gender,
children and region. The outcome is the expenses of health insurance
with some covariates about personal information.</p>
<p>Firstly is to check the class of each covariates in this dataset. Age
and bmi are continuous variables, “sex” “smoke” are binary variables,
and “region”“children” are categorical variables. To better predict
insurance charges, using continuous variables as the major predictor is
appropriate. Thus, We may see if there is a relationship between charges
and age or bmi, and determine the main predictor of insurance charges.
After that, we may determine which model has good fitness in our
data.</p>
<p><img src="index_files/figure-html/unnamed-chunk-1-1.png" width="672" /><img src="index_files/figure-html/unnamed-chunk-1-2.png" width="672" /></p>
<p>From the visualization of the data, charges lower than 15000 dollar
have more counts, and ony few people have very high expenses on
insurance (over 60000).There is a linear relationship between charges
and age, but no obvious patterns between charges and bmi. As the age
increases, we can see a trend of increasing charges from the
scatterplot. Then, I may consider to apply linear regression as my first
method. To improve the fitness of my linear regression model, I will
also add other covariates from this dataset in our model to check
linear’s least square estimates. Even though I did not see a significant
relationship between charges and bmi, it may also be needed in a linear
model. Finally I will split the data into training and testing sets to
check my linear model’s accuracy. Meanwhile, to get a more detailed
prediction of insurance charges, I will also apply machine learning
algorithms such as random forest to predict the outcome, and check this
algorithm’s performance compared with the linear model.</p>
</div>
<div id="analyzing" class="section level1">
<h1>Analyzing：</h1>
<div id="method-1" class="section level2">
<h2>method 1:</h2>
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" width="672" /><img src="index_files/figure-html/unnamed-chunk-2-2.png" width="672" /></p>
<p>We generate the training and data dataset to test the performance of
our model. In the linear model, adding one covariate age is obviously
not enough, and I have to select more variables from our data. From the
smoothing line of the ggplot, “Sex”, “region” is independent to
insurance charges. In the plot with sex as binary veriable, the dots
between male and sex is too close, and it is difficulty to determine
gender’s affect on charges. For the covariate region, the distribution
of charges in four region categories are even. Finally I will make
selections excluding these two covariates from our dataset.</p>
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" width="672" /><img src="index_files/figure-html/unnamed-chunk-3-2.png" width="672" /></p>
<p>In the plot above, it is obvious that green points with “yes smokers”
are throughly above the red points. The binary covariate “smoke”is
required for better fitness in our linear model.</p>
<p>The plot above is about the relationship between children and
charges. As the number of children one person has increases, the average
charge decreases. In the scatter plot, the trend is apparent when the
number of children increases from 3 to 5, and all points are below 20000
when a person has 5 children.</p>
<p>However, it is hard to determine whether or not bmi is necessary in
the linear, even though people at high bmi show high insurance charges.
We will see the RMSE change with or without bmi.</p>
<p>To test the performance of the linear model, I take 10% of data as
test sets and 90% as training tests. We will generate the model from the
training set.</p>
<pre><code>## # A tibble: 5 × 5
##   term        estimate std.error statistic   p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)  -12753.    1069.     -11.9  7.31e- 31
## 2 age             250.      13.5     18.6  6.36e- 67
## 3 children        596.     156.       3.83 1.38e-  4
## 4 smokeryes     23546.     466.      50.6  2.54e-285
## 5 bmi             351.      31.2     11.2  9.14e- 28</code></pre>
<pre><code>## [1] &quot;The adj square for model 1 is 0.740516517231389&quot;</code></pre>
<pre><code>## # A tibble: 4 × 5
##   term        estimate std.error statistic   p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)   -2688.     618.      -4.35 1.48e-  5
## 2 age             267.      14.1     18.9  5.51e- 69
## 3 children        583.     165.       3.54 4.11e-  4
## 4 smokeryes     23525.     492.      47.8  2.66e-267</code></pre>
<pre><code>## [1] &quot;The adj square for model 2 is 0.710024388085011&quot;</code></pre>
<pre><code>## [1] &quot;The RMSE for model 1 is 5829.74111996821&quot;</code></pre>
<pre><code>## [1] &quot;The RMSE for model 2 is 5922.4163776174&quot;</code></pre>
<pre><code>##      age children   smoker      bmi 
## 1.015554 1.001809 1.000594 1.013276</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>The tables shown above are fitted values for two linear models. All
variables in two tables are statistically significant since their
p-values are below 0.05. For the model with bmi, its adj R square is
0.738, RMSE is 5740. For mod2 without bmi, its adj R square is 0.715,
and its RMSE is 6154. The standard to choose the best fitted linear
model is to choose the model with biggest adjusted r square, or the
least RMSE. The results shown above show that the linear model with bmi
is better. I also tested linear model either with addition of sex or
region, and we don’t see increase of adj R square.</p>
<p>I have set age as the main predictor. We can interpret the linear
model as: for one unit increase in age, we expect to see 250 increase in
insurance charges, on average, holding all other covariates constant.
The intercept of this model is -12753.</p>
<p>For this model, I also test the variance inflation factor to
determine whether or not collinearity exists in a linear model, two
variables should not have strong correlations. Collinearity will let our
model mistakenly report adj R square. The result from VIF shows that all
variables in the model show VIF close to one, which means no
collinearity exists(these variables are almost independent with each
other). Then, I also plot the predicted charges versus actual charges in
test sets.</p>
<p>From the plot above, when the charges are below 20000, the prediction
is close to actual charges. However, when the charge gets higher, we see
many points deviate away from the fitted line. Our prediction can either
be too low or too high. Possibly, non-linear effects may exist in our
model, or there is effect modification between different terms. It is
hard to determine that linear is the best one to predict insurance
charges. Therefore, I may take another method to see whether or nor I
can improve my fitness or RMSE.</p>
</div>
<div id="method-2" class="section level2">
<h2>Method 2:</h2>
<p>The next method is to apply random forest to predict insurance
charges. This algorithm can generate many predictors, each using
classification trees to form a final prediction based on the average
prediction of all these trees. It has randomness and stability. We will
use the same training and test data set to see its performance.</p>
<pre><code>## [1] 4797.725</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" width="672" />
I set the training control as 6, and take mtry with the least RMSE. All
other settings are default. The output from random forest is better than
the linear model, and we get RMSE about 4282. The plot shown prediction
versus actual value performs much better than the situation in linear
model. At higher units of charges, the predicted value and actual value
are close. The most dots in this model stick to the abline. Even though
a few points at low quantity of charge deviate away from the fitted
line, this model’s performance has made a great improvement. These
points deviating away from the abline may be outliers, and every model
inevitably has certain outliers. Moreover, we don’t see a huge
difference of RMSE between linear model and random forest, which means
our initial approach is correct. Linear model, compared with this
algorithm, is much easier to interpret and understandable to audiences.
We can use the interpretation from the linear model to do predictions of
charges.</p>
</div>
</div>
<div id="conclusion" class="section level1">
<h1>Conclusion:</h1>
<p>Based on the analysis above, we concluded that bmi, age, smoking,
children number contributes to the prediction of insurance charges. The
best statistical model is linear regression. In EDA, covariate bmi does
not show specific patterns with charges. However, through the
calculation of RMSE across several linear models, we found that bmi is
required in linear models. The random forest method also shows slightly
lower RMSE compared with the linear.</p>
<p>Overall, our prediction by using a linear model is satisfying. Using
a linear model can catch most of the predictions in the test dataset.
Compared to random forest algorithms, it has low RMSE when the charges
are below 20000. Even though we may see certain outlier-like points in
linear models when the charges are high. The random forest algorithm is
successful since most points between prediction versus actual test value
fit the abline.</p>
<p>If I had more time, I would explore the non-linear effects of
covariates in our linear model, such as age and bmi. Or, I may explore
potential effect modifications or certain combinations of covariates. If
those approaches can decrease the RMSE further more, that means our
linear model still requires improvement.</p>
</div>
<div id="references" class="section level1">
<h1>References:</h1>
<p><a href="https://www.kaggle.com/datasets/mirichoi0218/insurance"
class="uri">https://www.kaggle.com/datasets/mirichoi0218/insurance</a></p>
</div>
<div id="appendix" class="section level1">
<h1>Appendix:</h1>
<pre class="r"><code>library(tidyverse)

dat&lt;-read_csv(&quot;https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/insurance.csv&quot;)



hist(dat$charges)


dat |&gt; 
ggplot(aes(age,charges)) + 
geom_point(alpha = 0.5)



dat|&gt;ggplot(aes(age,charges))+geom_point(aes(col=sex))

dat|&gt;ggplot(aes(region,charges))+geom_point()




dat|&gt;ggplot(aes(age,charges))+geom_point(aes(col=smoker))

dat|&gt;ggplot(aes(children,charges))+geom_point()




library(caret)
library(car)

set.seed(2018)

y&lt;-dat$charges
test_index &lt;- createDataPartition(y, times = 1, p = 0.2, list = FALSE)
test_set &lt;- dat[test_index, ]
train_set &lt;- dat[-test_index, ]

lm1&lt;-lm(charges~age+children+smoker+bmi,data=train_set)
lm2&lt;-lm(charges~age+children+smoker,data=train_set)


broom::tidy(lm1)
print(paste(&quot;The adj square for model 1 is&quot;,summary(lm1)$adj.r.squared))

broom::tidy(lm2)
print(paste(&quot;The adj square for model 2 is&quot;,summary(lm2)$adj.r.squared))

y_hat&lt;- predict(lm1, test_set)
print(paste(&quot;The RMSE for model 1 is&quot;,sqrt(mean((y_hat - test_set$charges)^2))))

y_hat1 &lt;- predict(lm2, test_set)
print(paste(&quot;The RMSE for model 2 is&quot;,sqrt(mean((y_hat1 - test_set$charges)^2))))

vif(lm1)

test_set|&gt; ggplot(aes(x = y_hat, y = charges)) + 
  geom_point() + 
  geom_abline(color = &quot;green&quot;)+ggtitle(&quot;actual versus prediction in linear model&quot;)
library(randomForest)


control &lt;- trainControl(method=&quot;cv&quot;, number = 6)
train_rf &lt;-  train(charges ~., method = &quot;rf&quot;,trControl = control,data=train_set )

fit_rf &lt;- randomForest(charges ~.,
                       mtry = train_rf$bestTune$mtry,data=train_set)

y_hat &lt;- predict(fit_rf,test_set)

RMSE(y_hat, test_set$charges)

test_set|&gt; ggplot(aes(x = y_hat, y = charges)) + 
  geom_point() + 
  geom_abline(color = &quot;green&quot;)



labs = knitr::all_labels()
labs = setdiff(labs, c(&quot;setup&quot;, &quot;get-labels&quot;))</code></pre>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
